/**
 * Idempotent import script.
 *
 * Parses CFID_Precedent_Library_Pilot.xlsx and Links.xlsx (never modifying
 * either file) and writes deterministic, fully-overwritten JSON into
 * src/data/generated/. Running this script any number of times produces the
 * same output for the same source workbooks — nothing is appended, so there
 * is no way for repeated runs to create duplicate records.
 *
 * Usage: npm run import:data
 */
import fs from "node:fs";
import path from "node:path";
import { parsePrecedentWorkbook } from "./lib/parsePrecedentWorkbook";
import { parseLinksWorkbook } from "./lib/parseLinksWorkbook";
import { REPO_ROOT } from "./lib/xlsxUtil";

const OUT_DIR = path.join(REPO_ROOT, "src", "data", "generated");

function writeJson(fileName: string, data: unknown) {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const filePath = path.join(OUT_DIR, fileName);
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n", "utf-8");
  console.log(`  wrote ${path.relative(REPO_ROOT, filePath)}`);
}

function main() {
  console.log("Importing CFID_Precedent_Library_Pilot.xlsx ...");
  const precedent = parsePrecedentWorkbook();
  console.log("Importing Links.xlsx ...");
  const links = parseLinksWorkbook();

  console.log("Writing generated data files:");
  writeJson("orders.json", precedent.orders);
  writeJson("scenarioFindings.json", precedent.scenarioFindings);
  writeJson("provisions.json", precedent.provisions);
  writeJson("legalTests.json", precedent.legalTests);
  writeJson("directions.json", precedent.directions);
  writeJson("pfutpFocus.json", precedent.pfutpFocus);
  writeJson("awaitingAnalysis.json", links.rows);
  writeJson(
    "meta.json",
    {
      generatedAt: new Date().toISOString(),
      sourceFiles: ["CFID_Precedent_Library_Pilot.xlsx", "Links.xlsx"],
      note: "Generated by scripts/import-data.ts. Do not hand-edit — re-run the import script instead.",
    }
  );

  const allWarnings = [...precedent.warnings, ...links.warnings];
  if (allWarnings.length > 0) {
    console.log(`\n${allWarnings.length} warning(s) during import:`);
    for (const w of allWarnings) console.log(`  - ${w}`);
  }

  console.log(
    `\nImported ${precedent.orders.length} orders, ${precedent.scenarioFindings.length} scenario findings, ` +
      `${precedent.provisions.length} provisions, ${links.rows.length} awaiting-analysis register rows.`
  );
  console.log("\nRun `npm run validate:data` to generate the validation report.");
}

main();
