/**
 * Idempotent import script.
 *
 * Parses CFID_Precedent_Library_Pilot.xlsx, Verified_CFID_Order_Links.xlsx
 * and Residual_Order_Links.xlsx (never modifying any of them) and writes
 * deterministic, fully-overwritten JSON into src/data/generated/. Running
 * this script any number of times produces the same output for the same
 * source workbooks — nothing is appended, so there is no way for repeated
 * runs to create duplicate records.
 *
 * The original Links.xlsx compilation is no longer used — see
 * Verified_CFID_Order_Links.xlsx (authoritative) and Residual_Order_Links.xlsx
 * (exclusion / pending-link register only).
 *
 * Usage: npm run import:data
 */
import fs from "node:fs";
import path from "node:path";
import { parsePrecedentWorkbook } from "./lib/parsePrecedentWorkbook";
import { parseVerifiedOrdersWorkbook } from "./lib/parseVerifiedOrdersWorkbook";
import { parseResidualWorkbook } from "./lib/parseResidualWorkbook";
import { REPO_ROOT } from "./lib/xlsxUtil";

const OUT_DIR = path.join(REPO_ROOT, "src", "data", "generated");

function writeJson(fileName: string, data: unknown) {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const filePath = path.join(OUT_DIR, fileName);
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n", "utf-8");
  console.log(`  wrote ${path.relative(REPO_ROOT, filePath)}`);
}

function main() {
  console.log("Importing CFID_Precedent_Library_Pilot.xlsx ...");
  const precedent = parsePrecedentWorkbook();
  console.log("Importing Verified_CFID_Order_Links.xlsx ...");
  const verified = parseVerifiedOrdersWorkbook(precedent.orders);
  console.log("Importing Residual_Order_Links.xlsx ...");
  const residual = parseResidualWorkbook();

  console.log("Writing generated data files:");
  writeJson("orders.json", precedent.orders);
  writeJson("scenarioFindings.json", precedent.scenarioFindings);
  writeJson("provisions.json", precedent.provisions);
  writeJson("legalTests.json", precedent.legalTests);
  writeJson("directions.json", precedent.directions);
  writeJson("pfutpFocus.json", precedent.pfutpFocus);
  writeJson("verifiedCfidOrders.json", verified.rows);
  writeJson("residualOrders.json", residual.rows);
  writeJson(
    "meta.json",
    {
      generatedAt: new Date().toISOString(),
      sourceFiles: [
        "CFID_Precedent_Library_Pilot.xlsx",
        "Verified_CFID_Order_Links.xlsx",
        "Residual_Order_Links.xlsx",
      ],
      note: "Generated by scripts/import-data.ts. Do not hand-edit — re-run the import script instead.",
    }
  );

  const allWarnings = [...precedent.warnings, ...verified.warnings, ...residual.warnings];
  if (allWarnings.length > 0) {
    console.log(`\n${allWarnings.length} warning(s) during import:`);
    for (const w of allWarnings) console.log(`  - ${w}`);
  }

  console.log(
    `\nImported ${precedent.orders.length} orders, ${precedent.scenarioFindings.length} scenario findings, ` +
      `${precedent.provisions.length} provisions, ${verified.rows.length} verified CFID order rows, ` +
      `${residual.rows.length} residual register rows.`
  );
  console.log("\nRun `npm run validate:data` to generate the validation report.");
}

main();
